Fix installation on windows
Error traceback:

```
Collecting git+https://github.com/zergov/flashcards.git
  Cloning https://github.com/zergov/flashcards.git to \temp\pip-req-build-y1h2ngk0
  Running command git clone --filter=blob:none --quiet https://github.com/zergov/flashcards.git '\Temp\pip-req-build-y1h2ngk0'
  Resolved https://github.com/zergov/flashcards.git to commit 4d1b1c277585b95517ed6c00ceff7555c8c131eb
  Preparing metadata (setup.py) ... done
Collecting click==6.6 (from pyflashcards==1.0.2)
  Using cached click-6.6-py2.py3-none-any.whl.metadata (424 bytes)
Using cached click-6.6-py2.py3-none-any.whl (71 kB)
Building wheels for collected packages: pyflashcards
  Building wheel for pyflashcards (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\flashcards
      copying flashcards\cards.py -> build\lib\flashcards
      copying flashcards\main.py -> build\lib\flashcards
      copying flashcards\sets.py -> build\lib\flashcards
      copying flashcards\storage.py -> build\lib\flashcards
      copying flashcards\study.py -> build\lib\flashcards
      copying flashcards\__init__.py -> build\lib\flashcards
      creating build\lib\flashcards\commands
      copying flashcards\commands\cards.py -> build\lib\flashcards\commands
      copying flashcards\commands\sets.py -> build\lib\flashcards\commands
      copying flashcards\commands\__init__.py -> build\lib\flashcards\commands
      creating build\lib\flashcards\utils
      copying flashcards\utils\storage.py -> build\lib\flashcards\utils
      copying flashcards\utils\__init__.py -> build\lib\flashcards\utils
      \Python311\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\flashcards
      copying build\lib\flashcards\cards.py -> build\bdist.win-amd64\wheel\.\flashcards
      creating build\bdist.win-amd64\wheel\flashcards\commands
      copying build\lib\flashcards\commands\cards.py -> build\bdist.win-amd64\wheel\.\flashcards\commands
      copying build\lib\flashcards\commands\sets.py -> build\bdist.win-amd64\wheel\.\flashcards\commands
      copying build\lib\flashcards\commands\__init__.py -> build\bdist.win-amd64\wheel\.\flashcards\commands
      copying build\lib\flashcards\main.py -> build\bdist.win-amd64\wheel\.\flashcards
      copying build\lib\flashcards\sets.py -> build\bdist.win-amd64\wheel\.\flashcards
      copying build\lib\flashcards\storage.py -> build\bdist.win-amd64\wheel\.\flashcards
      copying build\lib\flashcards\study.py -> build\bdist.win-amd64\wheel\.\flashcards
      creating build\bdist.win-amd64\wheel\flashcards\utils
      copying build\lib\flashcards\utils\storage.py -> build\bdist.win-amd64\wheel\.\flashcards\utils
      copying build\lib\flashcards\utils\__init__.py -> build\bdist.win-amd64\wheel\.\flashcards\utils
      copying build\lib\flashcards\__init__.py -> build\bdist.win-amd64\wheel\.\flashcards
      running install_data
      creating build\bdist.win-amd64\wheel\pyflashcards-1.0.2.data
      creating build\bdist.win-amd64\wheel\pyflashcards-1.0.2.data\data
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "\Temp\pip-req-build-y1h2ngk0\setup.py", line 9, in <module>
          setup(
        File "\Python311\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "\Python311\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "\Python311\Lib\site-packages\setuptools\command\bdist_wheel.py", line 408, in run
          self.run_command("install")
        File "\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "\Python311\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "\Python311\Lib\site-packages\setuptools\command\install.py", line 81, in run
          return super().run()
                 ^^^^^^^^^^^^^
        File "\Python311\Lib\site-packages\setuptools\_distutils\command\install.py", line 708, in run
          self.run_command(cmd_name)
        File "\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "\Python311\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "\Python311\Lib\site-packages\setuptools\_distutils\command\install_data.py", line 61, in run
          dir = convert_path(f[0])
                ^^^^^^^^^^^^^^^^^^
        File "\Python311\Lib\site-packages\setuptools\_distutils\util.py", line 132, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/etc/bash_completion.d/' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyflashcards
  Running setup.py clean for pyflashcards
Failed to build pyflashcards
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyflashcards)
```