Fix error writing to temp file on `flashcards add -e`
NamedTemporaryFile by default is using "bytes" mode and there is an error because we're trying to write a string.

Traceback:
```
>flashcards cards add -e
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\Python311\Scripts\flashcards.exe\__main__.py", line 7, in <module>
  File "\Python311\Lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\flashcards\commands\cards.py", line 30, in add
    question = _ask_for_question(editormode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\flashcards\commands\cards.py", line 51, in _ask_for_question
    return prompt_via_editor('TMP_QUESTION_', message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\site-packages\flashcards\commands\cards.py", line 81, in prompt_via_editor
    f.write(init_message)
  File "\Python311\Lib\tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```